# Generated by Django 4.2.3 on 2023-07-22 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_todolist_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='owner',
        ),
    ]
