# Generated by Django 4.2.3 on 2023-07-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_todolist_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
